version: '3'

services:
  sandbox:
    container_name: sandbox
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/go/src/sandbox
    tty: true # persistence
    environment:
      - TZ=Asia/Tokyo
